export const SEED_CATEGORIES = [
  { id: 'cat-ai', name: 'Artificial Intelligence', icon: 'Bot', description: 'Deep learning, LLMs, computer vision, and neural systems' },
  { id: 'cat-ml', name: 'Machine Learning', icon: 'Cpu', description: 'Predictive modeling, data analytics, and statistical algorithms' },
  { id: 'cat-web', name: 'Web Development', icon: 'Globe', description: 'Modern full-stack web applications, APIs, and microservices' },
  { id: 'cat-cloud', name: 'Cloud Computing', icon: 'Cloud', description: 'Serverless architectures, Kubernetes, microservices, and distributed systems' },
  { id: 'cat-sec', name: 'Cybersecurity', icon: 'Shield', description: 'Network security, cryptography, vulnerability assessment, and zero trust' },
  { id: 'cat-data', name: 'Data Science', icon: 'Database', description: 'Big data pipelines, visualization, ETL, and statistical insights' },
  { id: 'cat-iot', name: 'Internet of Things (IoT)', icon: 'Wifi', description: 'Embedded systems, microcontrollers, edge computing, and sensors' },
  { id: 'cat-mobile', name: 'Mobile Development', icon: 'Smartphone', description: 'Cross-platform iOS and Android apps with React Native or Flutter' },
  { id: 'cat-blockchain', name: 'Blockchain & Web3', icon: 'Layers', description: 'Smart contracts, decentralized ledgers, and tokenomics' },
  { id: 'cat-health', name: 'Healthcare & Biotech', icon: 'HeartPulse', description: 'Medical imaging, telemedicine, health records, and bioinformatics' },
  { id: 'cat-sustain', name: 'Sustainability & Green Tech', icon: 'Leaf', description: 'Carbon footprint trackers, energy optimization, and eco-analytics' },
  { id: 'cat-campus', name: 'Smart Campus & Education', icon: 'GraduationCap', description: 'Campus navigation, student lifecycle, and ed-tech platforms' },
  { id: 'cat-auto', name: 'Automation & Robotics', icon: 'Zap', description: 'RPA pipelines, autonomous bots, and workflow orchestrators' },
  { id: 'cat-arvr', name: 'AR / VR & Gaming', icon: 'Sparkles', description: 'Immersive simulations, 3D spatial web, and interactive media' },
];

export const SEED_SKILLS = [
  // Technical - Languages
  { id: 'sk-py', name: 'Python', category: 'Languages', domain: 'Backend' },
  { id: 'sk-js', name: 'JavaScript', category: 'Languages', domain: 'Frontend' },
  { id: 'sk-ts', name: 'TypeScript', category: 'Languages', domain: 'Frontend' },
  { id: 'sk-java', name: 'Java', category: 'Languages', domain: 'Backend' },
  { id: 'sk-cpp', name: 'C++', category: 'Languages', domain: 'Systems' },
  { id: 'sk-go', name: 'Go (Golang)', category: 'Languages', domain: 'Backend' },
  { id: 'sk-rust', name: 'Rust', category: 'Languages', domain: 'Systems' },
  { id: 'sk-html', name: 'HTML5', category: 'Frontend', domain: 'Frontend' },
  { id: 'sk-css', name: 'CSS3 / Tailwind', category: 'Frontend', domain: 'Frontend' },

  // Technical - Frameworks & Libraries
  { id: 'sk-react', name: 'React', category: 'Frontend', domain: 'Frontend' },
  { id: 'sk-next', name: 'Next.js', category: 'Frontend', domain: 'Frontend' },
  { id: 'sk-vue', name: 'Vue.js', category: 'Frontend', domain: 'Frontend' },
  { id: 'sk-node', name: 'Node.js', category: 'Backend', domain: 'Backend' },
  { id: 'sk-express', name: 'Express.js', category: 'Backend', domain: 'Backend' },
  { id: 'sk-flask', name: 'Flask', category: 'Backend', domain: 'Backend' },
  { id: 'sk-fastapi', name: 'FastAPI', category: 'Backend', domain: 'Backend' },
  { id: 'sk-django', name: 'Django', category: 'Backend', domain: 'Backend' },

  // Technical - Cloud & DevOps
  { id: 'sk-firebase', name: 'Firebase', category: 'Cloud & DevOps', domain: 'Cloud/DevOps' },
  { id: 'sk-aws', name: 'AWS Cloud', category: 'Cloud & DevOps', domain: 'Cloud/DevOps' },
  { id: 'sk-gcp', name: 'Google Cloud Platform', category: 'Cloud & DevOps', domain: 'Cloud/DevOps' },
  { id: 'sk-docker', name: 'Docker', category: 'Cloud & DevOps', domain: 'Cloud/DevOps' },
  { id: 'sk-k8s', name: 'Kubernetes', category: 'Cloud & DevOps', domain: 'Cloud/DevOps' },
  { id: 'sk-cicd', name: 'CI/CD Pipelines', category: 'Cloud & DevOps', domain: 'Cloud/DevOps' },

  // Technical - AI & Data
  { id: 'sk-ml', name: 'Machine Learning', category: 'AI & Data', domain: 'AI/ML' },
  { id: 'sk-dl', name: 'Deep Learning', category: 'AI & Data', domain: 'AI/ML' },
  { id: 'sk-cv', name: 'Computer Vision', category: 'AI & Data', domain: 'AI/ML' },
  { id: 'sk-nlp', name: 'Natural Language Processing', category: 'AI & Data', domain: 'AI/ML' },
  { id: 'sk-tf', name: 'TensorFlow / Keras', category: 'AI & Data', domain: 'AI/ML' },
  { id: 'sk-pytorch', name: 'PyTorch', category: 'AI & Data', domain: 'AI/ML' },
  { id: 'sk-pandas', name: 'Pandas & NumPy', category: 'AI & Data', domain: 'Data Science' },
  { id: 'sk-sql', name: 'MySQL / PostgreSQL', category: 'Databases', domain: 'Backend' },
  { id: 'sk-mongo', name: 'MongoDB', category: 'Databases', domain: 'Backend' },

  // UI/UX & Design
  { id: 'sk-uiux', name: 'UI/UX Design', category: 'Design', domain: 'UI/UX' },
  { id: 'sk-figma', name: 'Figma', category: 'Design', domain: 'UI/UX' },

  // Security & Hardware
  { id: 'sk-sec', name: 'Cybersecurity & Pentesting', category: 'Security', domain: 'Cybersecurity' },
  { id: 'sk-iot', name: 'IoT & Arduino / Raspberry Pi', category: 'Hardware', domain: 'IoT' },
  { id: 'sk-git', name: 'Git & Version Control', category: 'Tools', domain: 'DevOps' },
];

export const SOFT_SKILLS_LIST = [
  'Communication',
  'Teamwork',
  'Leadership',
  'Presentation',
  'Research',
  'Documentation',
  'Problem Solving',
  'Critical Thinking',
  'Agile / Scrum',
  'Time Management'
];

export const SEED_STUDENTS = [
  {
    id: 'user-alex',
    name: 'Alex Chen',
    email: 'alex.chen@clouduniv.edu',
    role: 'student',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    college: 'School of Computing & Data Sciences',
    department: 'Computer Science & Engineering',
    year: '3rd Year',
    experienceLevel: 'Intermediate',
    bio: 'Passionate full-stack developer and cloud architect enthusiast. Love building real-time collaborative apps and scalable backend pipelines.',
    technicalSkills: [
      { name: 'Python', level: 'Advanced' },
      { name: 'JavaScript', level: 'Advanced' },
      { name: 'React', level: 'Intermediate' },
      { name: 'Firebase', level: 'Advanced' },
      { name: 'FastAPI', level: 'Intermediate' },
      { name: 'Docker', level: 'Intermediate' },
      { name: 'Git & Version Control', level: 'Advanced' },
    ],
    softSkills: ['Leadership', 'Problem Solving', 'Teamwork', 'Communication'],
    interests: ['Cloud Computing', 'Artificial Intelligence', 'Web Development', 'Smart Campus'],
    preferredTechnologies: ['React', 'Python', 'Firebase', 'Docker', 'FastAPI', 'Tailwind'],
    createdAt: '2026-01-10T10:00:00Z',
  },
  {
    id: 'user-sophia',
    name: 'Sophia Patel',
    email: 'sophia.patel@clouduniv.edu',
    role: 'student',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&auto=format&fit=crop&q=80',
    college: 'School of Artificial Intelligence',
    department: 'AI & Data Science',
    year: '4th Year',
    experienceLevel: 'Advanced',
    bio: 'Machine Learning researcher focused on Computer Vision and sustainable environmental AI solutions. Looking for UI/UX teammates!',
    technicalSkills: [
      { name: 'Python', level: 'Advanced' },
      { name: 'PyTorch', level: 'Advanced' },
      { name: 'Machine Learning', level: 'Advanced' },
      { name: 'Computer Vision', level: 'Advanced' },
      { name: 'Deep Learning', level: 'Intermediate' },
      { name: 'Pandas & NumPy', level: 'Advanced' },
      { name: 'Flask', level: 'Intermediate' },
    ],
    softSkills: ['Research', 'Documentation', 'Critical Thinking', 'Problem Solving'],
    interests: ['Artificial Intelligence', 'Machine Learning', 'Sustainability & Green Tech', 'Healthcare & Biotech'],
    preferredTechnologies: ['PyTorch', 'Python', 'OpenCV', 'Pandas & NumPy', 'AWS Cloud'],
    createdAt: '2026-01-12T11:30:00Z',
  },
  {
    id: 'user-marcus',
    name: 'Marcus Brody',
    email: 'marcus.brody@clouduniv.edu',
    role: 'student',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    college: 'School of Design & Informatics',
    department: 'Human-Computer Interaction',
    year: '3rd Year',
    experienceLevel: 'Intermediate',
    bio: 'Product designer and frontend engineer. Obsessed with 3D web experiences, micro-interactions, Figma component libraries, and clean UX.',
    technicalSkills: [
      { name: 'UI/UX Design', level: 'Advanced' },
      { name: 'Figma', level: 'Advanced' },
      { name: 'React', level: 'Advanced' },
      { name: 'TypeScript', level: 'Intermediate' },
      { name: 'CSS3 / Tailwind', level: 'Advanced' },
      { name: 'HTML5', level: 'Advanced' },
      { name: 'JavaScript', level: 'Advanced' },
    ],
    softSkills: ['Presentation', 'Communication', 'Teamwork', 'Agile / Scrum'],
    interests: ['Web Development', 'AR / VR & Gaming', 'Smart Campus', 'Healthcare & Biotech'],
    preferredTechnologies: ['Figma', 'React', 'TypeScript', 'Tailwind', 'Next.js'],
    createdAt: '2026-01-15T09:15:00Z',
  },
  {
    id: 'user-elena',
    name: 'Elena Rostova',
    email: 'elena.rostova@clouduniv.edu',
    role: 'student',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200&auto=format&fit=crop&q=80',
    college: 'School of Information Security',
    department: 'Cybersecurity & Network Defense',
    year: '4th Year',
    experienceLevel: 'Advanced',
    bio: 'Security researcher and ethical hacker. Interested in zero-trust architectures, cryptography protocols, and cloud intrusion defense.',
    technicalSkills: [
      { name: 'Cybersecurity & Pentesting', level: 'Advanced' },
      { name: 'Python', level: 'Advanced' },
      { name: 'Go (Golang)', level: 'Intermediate' },
      { name: 'Docker', level: 'Advanced' },
      { name: 'Kubernetes', level: 'Intermediate' },
      { name: 'MySQL / PostgreSQL', level: 'Intermediate' },
    ],
    softSkills: ['Problem Solving', 'Critical Thinking', 'Leadership', 'Documentation'],
    interests: ['Cybersecurity', 'Cloud Computing', 'Blockchain & Web3', 'Automation & Robotics'],
    preferredTechnologies: ['Go (Golang)', 'Docker', 'Kubernetes', 'Python', 'Linux'],
    createdAt: '2026-01-18T14:45:00Z',
  },
  {
    id: 'user-rohit',
    name: 'Rohit Sharma',
    email: 'rohit.sharma@clouduniv.edu',
    role: 'student',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
    college: 'School of Electrical & Electronics',
    department: 'Embedded Systems & IoT',
    year: '3rd Year',
    experienceLevel: 'Intermediate',
    bio: 'Hardware geek building smart campus sensor arrays and edge-computing microcontrollers. Looking for backend cloud developers.',
    technicalSkills: [
      { name: 'IoT & Arduino / Raspberry Pi', level: 'Advanced' },
      { name: 'C++', level: 'Advanced' },
      { name: 'Python', level: 'Intermediate' },
      { name: 'MySQL / PostgreSQL', level: 'Intermediate' },
      { name: 'Firebase', level: 'Intermediate' },
    ],
    softSkills: ['Teamwork', 'Time Management', 'Research', 'Problem Solving'],
    interests: ['Internet of Things (IoT)', 'Smart Campus', 'Sustainability & Green Tech', 'Automation & Robotics'],
    preferredTechnologies: ['C++', 'IoT & Arduino / Raspberry Pi', 'Python', 'Firebase'],
    createdAt: '2026-01-20T16:20:00Z',
  },
  {
    id: 'user-maya',
    name: 'Maya Lin',
    email: 'maya.lin@clouduniv.edu',
    role: 'student',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&auto=format&fit=crop&q=80',
    college: 'School of Computing',
    department: 'Cloud Computing & DevOps',
    year: '2nd Year',
    experienceLevel: 'Beginner',
    bio: 'Eager 2nd-year student eager to learn Kubernetes, AWS cloud deployment pipelines, and microservices clustering.',
    technicalSkills: [
      { name: 'JavaScript', level: 'Intermediate' },
      { name: 'HTML5', level: 'Advanced' },
      { name: 'CSS3 / Tailwind', level: 'Intermediate' },
      { name: 'Docker', level: 'Beginner' },
      { name: 'AWS Cloud', level: 'Beginner' },
      { name: 'Git & Version Control', level: 'Intermediate' },
    ],
    softSkills: ['Communication', 'Presentation', 'Teamwork', 'Time Management'],
    interests: ['Cloud Computing', 'Web Development', 'Smart Campus'],
    preferredTechnologies: ['AWS Cloud', 'Docker', 'React', 'Node.js'],
    createdAt: '2026-01-22T08:10:00Z',
  },
  {
    id: 'user-tariq',
    name: 'Tariq Al-Mansoor',
    email: 'tariq.mansoor@clouduniv.edu',
    role: 'student',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=200&auto=format&fit=crop&q=80',
    college: 'School of Software Engineering',
    department: 'Distributed Systems',
    year: '4th Year',
    experienceLevel: 'Advanced',
    bio: 'Backend specialist with experience building high-throughput microservices using Go, gRPC, and Redis.',
    technicalSkills: [
      { name: 'Go (Golang)', level: 'Advanced' },
      { name: 'Docker', level: 'Advanced' },
      { name: 'Kubernetes', level: 'Advanced' },
      { name: 'MySQL / PostgreSQL', level: 'Advanced' },
      { name: 'CI/CD Pipelines', level: 'Intermediate' },
      { name: 'Python', level: 'Intermediate' },
    ],
    softSkills: ['Leadership', 'Problem Solving', 'Architecture Design', 'Mentorship'],
    interests: ['Cloud Computing', 'Cybersecurity', 'Web Development', 'Blockchain & Web3'],
    preferredTechnologies: ['Go (Golang)', 'Kubernetes', 'Docker', 'PostgreSQL', 'GCP'],
    createdAt: '2026-01-25T13:00:00Z',
  },
  {
    id: 'user-aisha',
    name: 'Aisha Bello',
    email: 'aisha.bello@clouduniv.edu',
    role: 'student',
    avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=200&auto=format&fit=crop&q=80',
    college: 'School of Health Informatics',
    department: 'Bio-Medical Data Engineering',
    year: '3rd Year',
    experienceLevel: 'Intermediate',
    bio: 'Bridging healthcare and machine learning. Creating patient diagnostic triage platforms with privacy-preserving models.',
    technicalSkills: [
      { name: 'Python', level: 'Advanced' },
      { name: 'Machine Learning', level: 'Intermediate' },
      { name: 'Pandas & NumPy', level: 'Advanced' },
      { name: 'React', level: 'Intermediate' },
      { name: 'MySQL / PostgreSQL', level: 'Intermediate' },
    ],
    softSkills: ['Research', 'Documentation', 'Communication', 'Ethics'],
    interests: ['Healthcare & Biotech', 'Machine Learning', 'Data Science', 'Sustainability & Green Tech'],
    preferredTechnologies: ['Python', 'React', 'FastAPI', 'Pandas & NumPy'],
    createdAt: '2026-01-28T15:10:00Z',
  },
  {
    id: 'user-lucas',
    name: 'Lucas Silva',
    email: 'lucas.silva@clouduniv.edu',
    role: 'student',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200&auto=format&fit=crop&q=80',
    college: 'School of Computing',
    department: 'Mobile & Cloud Applications',
    year: '3rd Year',
    experienceLevel: 'Intermediate',
    bio: 'Mobile developer building React Native and Flutter apps connected to Firebase and cloud serverless functions.',
    technicalSkills: [
      { name: 'JavaScript', level: 'Advanced' },
      { name: 'TypeScript', level: 'Intermediate' },
      { name: 'React', level: 'Advanced' },
      { name: 'Firebase', level: 'Advanced' },
      { name: 'Node.js', level: 'Intermediate' },
      { name: 'UI/UX Design', level: 'Intermediate' },
    ],
    softSkills: ['Teamwork', 'Agile / Scrum', 'Problem Solving', 'Creativity'],
    interests: ['Mobile Development', 'Web Development', 'Smart Campus', 'AR / VR & Gaming'],
    preferredTechnologies: ['React', 'Firebase', 'TypeScript', 'Tailwind'],
    createdAt: '2026-01-30T10:40:00Z',
  },
  {
    id: 'user-priya',
    name: 'Priya Nair',
    email: 'priya.nair@clouduniv.edu',
    role: 'student',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&auto=format&fit=crop&q=80',
    college: 'School of Computing',
    department: 'Artificial Intelligence & NLP',
    year: '4th Year',
    experienceLevel: 'Advanced',
    bio: 'NLP and LLM enthusiast. Building smart conversational agents and document semantic search pipelines with LangChain and vector databases.',
    technicalSkills: [
      { name: 'Python', level: 'Advanced' },
      { name: 'Natural Language Processing', level: 'Advanced' },
      { name: 'PyTorch', level: 'Intermediate' },
      { name: 'FastAPI', level: 'Advanced' },
      { name: 'Docker', level: 'Intermediate' },
      { name: 'MongoDB', level: 'Intermediate' },
    ],
    softSkills: ['Leadership', 'Presentation', 'Research', 'Critical Thinking'],
    interests: ['Artificial Intelligence', 'Data Science', 'Smart Campus', 'Education'],
    preferredTechnologies: ['Python', 'FastAPI', 'PyTorch', 'MongoDB', 'Docker'],
    createdAt: '2026-02-01T11:20:00Z',
  }
];

export const SEED_ADMIN = {
  id: 'admin-robert',
  name: 'Prof. Robert Vance',
  email: 'robert.vance@clouduniv.edu',
  role: 'admin',
  avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&auto=format&fit=crop&q=80',
  college: 'Faculty of Computer Science & Cloud Engineering',
  department: 'Department Chair & Academic Project Coordinator',
  year: 'Faculty Staff',
  experienceLevel: 'Advanced',
  bio: 'Faculty Coordinator for Capstone Projects and Cloud Architecture Research. Guiding student teams towards industry-grade project outcomes.',
  technicalSkills: [
    { name: 'Cloud Computing', level: 'Advanced' },
    { name: 'AWS Cloud', level: 'Advanced' },
    { name: 'Docker', level: 'Advanced' },
    { name: 'Kubernetes', level: 'Advanced' },
  ],
  softSkills: ['Leadership', 'Mentorship', 'Curriculum Design', 'Evaluation'],
  interests: ['Cloud Computing', 'Artificial Intelligence', 'Cybersecurity', 'Smart Campus'],
  preferredTechnologies: ['AWS Cloud', 'Kubernetes', 'Docker', 'Python'],
  createdAt: '2025-08-01T00:00:00Z',
};

export const SEED_PROJECTS = [
  {
    id: 'proj-waste-ai',
    title: 'AI-Based Campus Waste Classification & Analytics',
    description: 'An intelligent smart-bin camera system utilizing computer vision and edge AI models to automatically classify recyclable, compostable, and landfill waste in real-time, streaming analytics to a cloud dashboard.',
    category: 'Artificial Intelligence',
    difficulty: 'Intermediate',
    requiredSkills: ['Python', 'Computer Vision', 'Machine Learning', 'Firebase'],
    technologies: ['Python', 'PyTorch', 'OpenCV', 'Firebase', 'React'],
    teamSize: '3-4',
    maxMembers: 4,
    duration: '4 Months',
    objective: 'Reduce campus landfill contamination by 40% through real-time automated sorting classification and gamified student sustainability incentives.',
    expectedOutcome: 'Working IoT camera prototype linked to a web dashboard with live classification analytics and student leaderboards.',
    createdBy: 'Prof. Robert Vance',
    createdById: 'admin-robert',
    createdAt: '2026-01-10T10:00:00Z',
    status: 'In Progress',
    featured: true,
  },
  {
    id: 'proj-smart-energy',
    title: 'Cloud-Connected Smart Campus Energy Optimizer',
    description: 'IoT sensor mesh network monitoring classroom energy consumption, HVAC load, and solar generation with predictive machine learning algorithms to automate dynamic power throttling.',
    category: 'Internet of Things (IoT)',
    difficulty: 'Intermediate',
    requiredSkills: ['IoT & Arduino / Raspberry Pi', 'Python', 'Firebase', 'React'],
    technologies: ['C++', 'Python', 'Firebase', 'React', 'Tailwind'],
    teamSize: '3-4',
    maxMembers: 4,
    duration: '3.5 Months',
    objective: 'Implement adaptive energy management across university labs to curtail peak grid consumption by 25%.',
    expectedOutcome: 'Multi-node sensor telemetry streaming to a real-time reactive cloud dashboard with predictive HVAC automation.',
    createdBy: 'Prof. Robert Vance',
    createdById: 'admin-robert',
    createdAt: '2026-01-14T11:00:00Z',
    status: 'Planning',
    featured: true,
  },
  {
    id: 'proj-micro-cloud',
    title: 'Serverless Edge Microservices for Campus Transit',
    description: 'High-concurrency distributed backend microservice pipeline tracking campus shuttle locations via GPS, computing dynamic ETAs using graph route algorithms, and broadcasting live WebSockets.',
    category: 'Cloud Computing',
    difficulty: 'Advanced',
    requiredSkills: ['Go (Golang)', 'Docker', 'Kubernetes', 'CI/CD Pipelines'],
    technologies: ['Go (Golang)', 'Docker', 'Kubernetes', 'AWS Cloud', 'React'],
    teamSize: '4-5',
    maxMembers: 5,
    duration: '5 Months',
    objective: 'Deliver sub-100ms real-time bus tracking and ETA updates to 15,000 concurrent student app users without server degradation.',
    expectedOutcome: 'Containerized Kubernetes microservice cluster deployed on AWS with high-availability load balancing.',
    createdBy: 'Prof. Robert Vance',
    createdById: 'admin-robert',
    createdAt: '2026-01-18T14:30:00Z',
    status: 'In Progress',
    featured: true,
  },
  {
    id: 'proj-zero-trust',
    title: 'Zero-Trust Identity & Access Verifier for Lab Infrastructure',
    description: 'Cryptographic authentication system verifying researcher access to sensitive quantum simulation rigs using hardware tokens, dynamic biometric risk scoring, and decentralized audit trails.',
    category: 'Cybersecurity',
    difficulty: 'Advanced',
    requiredSkills: ['Cybersecurity & Pentesting', 'Python', 'Docker', 'MySQL / PostgreSQL'],
    technologies: ['Python', 'Docker', 'PostgreSQL', 'Linux', 'FastAPI'],
    teamSize: '3-4',
    maxMembers: 4,
    duration: '4.5 Months',
    objective: 'Protect institutional research assets against unauthorized privilege escalation through automated zero-trust authorization.',
    expectedOutcome: 'Hardened identity gateway API and security auditor console with automated anomaly detection.',
    createdBy: 'Prof. Robert Vance',
    createdById: 'admin-robert',
    createdAt: '2026-01-20T09:00:00Z',
    status: 'Planning',
    featured: false,
  },
  {
    id: 'proj-tele-triage',
    title: 'AI Medical Tele-Triage & Symptom Visualizer',
    description: 'Patient-facing mobile-first application using natural language diagnostic models to prioritize student health clinic appointments, visualize symptom severity, and integrate with emergency services.',
    category: 'Healthcare & Biotech',
    difficulty: 'Intermediate',
    requiredSkills: ['React', 'Python', 'Natural Language Processing', 'UI/UX Design'],
    technologies: ['React', 'Python', 'FastAPI', 'Figma', 'Tailwind'],
    teamSize: '3-4',
    maxMembers: 4,
    duration: '4 Months',
    objective: 'Streamline campus clinic intake queues, cutting wait times for acute cases by 50% while maintaining strict HIPAA/FERPA privacy.',
    expectedOutcome: 'Responsive web application with interactive 3D anatomy symptom selector and triage clinician portal.',
    createdBy: 'Prof. Robert Vance',
    createdById: 'admin-robert',
    createdAt: '2026-01-22T12:00:00Z',
    status: 'In Progress',
    featured: true,
  },
  {
    id: 'proj-decentralized-cred',
    title: 'Decentralized Academic Credential & Skill Verifier',
    description: 'Tamper-proof academic diploma and verified skill credential verification network built with smart contracts and cryptographic verifiable credentials for immediate employer validation.',
    category: 'Blockchain & Web3',
    difficulty: 'Advanced',
    requiredSkills: ['JavaScript', 'TypeScript', 'Docker', 'MySQL / PostgreSQL'],
    technologies: ['TypeScript', 'Node.js', 'React', 'Docker', 'PostgreSQL'],
    teamSize: '3-4',
    maxMembers: 4,
    duration: '4 Months',
    objective: 'Eliminate resume credential fraud by generating cryptographically signed, zero-knowledge verifiable proof certificates.',
    expectedOutcome: 'Public verification portal and student credential wallet with 1-click LinkedIn instant badge verification.',
    createdBy: 'Prof. Robert Vance',
    createdById: 'admin-robert',
    createdAt: '2026-01-25T15:00:00Z',
    status: 'Planning',
    featured: false,
  },
  {
    id: 'proj-course-rag',
    title: 'Intelligent Course Assistant & RAG Semantic Search',
    description: 'Conversational study companion indexed on lecture slide PDFs, syllabus notes, and video transcripts using Retrieval-Augmented Generation (RAG) and semantic vector embeddings.',
    category: 'Artificial Intelligence',
    difficulty: 'Intermediate',
    requiredSkills: ['Python', 'Natural Language Processing', 'FastAPI', 'React'],
    technologies: ['Python', 'FastAPI', 'React', 'MongoDB', 'Tailwind'],
    teamSize: '2-3',
    maxMembers: 3,
    duration: '3 Months',
    objective: 'Enable 24/7 personalized academic question answering grounded strictly in professor-approved course materials.',
    expectedOutcome: 'Interactive chat interface with cited page references and interactive flashcard generator.',
    createdBy: 'Prof. Robert Vance',
    createdById: 'admin-robert',
    createdAt: '2026-01-28T10:15:00Z',
    status: 'In Progress',
    featured: true,
  },
  {
    id: 'proj-smart-attendance',
    title: 'Facial Recognition Automated Lecture Attendance',
    description: 'High-speed classroom camera attendance logger using lightweight face detection and anti-spoofing liveness checks to register student presence seamlessly upon entering.',
    category: 'Machine Learning',
    difficulty: 'Intermediate',
    requiredSkills: ['Python', 'Computer Vision', 'Machine Learning', 'MySQL / PostgreSQL'],
    technologies: ['Python', 'OpenCV', 'PyTorch', 'PostgreSQL', 'Flask'],
    teamSize: '3-4',
    maxMembers: 4,
    duration: '3.5 Months',
    objective: 'Recover 10 minutes of lost instructional lecture time per session by automating roll call with 99.2% accuracy.',
    expectedOutcome: 'Lecturer control tablet UI with real-time class headcount and exportable CSV attendance reports.',
    createdBy: 'Prof. Robert Vance',
    createdById: 'admin-robert',
    createdAt: '2026-01-30T16:00:00Z',
    status: 'Planning',
    featured: false,
  },
  {
    id: 'proj-campus-social',
    title: 'Micro-Community Campus Event & Study Group Hub',
    description: 'Modern real-time social platform allowing students to discover pop-up study rooms, hackathon teammates, and club events with interactive campus map integration.',
    category: 'Web Development',
    difficulty: 'Beginner',
    requiredSkills: ['JavaScript', 'HTML5', 'CSS3 / Tailwind', 'Firebase'],
    technologies: ['React', 'Firebase', 'Tailwind', 'JavaScript'],
    teamSize: '2-3',
    maxMembers: 3,
    duration: '2.5 Months',
    objective: 'Boost campus student collaboration and extracurricular engagement through geo-located spontaneous meetup rooms.',
    expectedOutcome: 'PWA with real-time chat rooms, calendar syncing, and interactive campus map overlays.',
    createdBy: 'Prof. Robert Vance',
    createdById: 'admin-robert',
    createdAt: '2026-02-02T13:00:00Z',
    status: 'In Progress',
    featured: false,
  },
  {
    id: 'proj-food-rescue',
    title: 'Campus Food Rescue & Surplus Meal Logistics Engine',
    description: 'Logistics coordination mobile web app connecting university cafeterias and catered events with student pantry distribution centers to eliminate food waste.',
    category: 'Sustainability & Green Tech',
    difficulty: 'Beginner',
    requiredSkills: ['React', 'JavaScript', 'Firebase', 'UI/UX Design'],
    technologies: ['React', 'Firebase', 'Figma', 'Tailwind'],
    teamSize: '2-3',
    maxMembers: 3,
    duration: '2.5 Months',
    objective: 'Redistribute over 500 lbs of surplus prepared campus meals weekly to food-insecure students in under 45 minutes.',
    expectedOutcome: 'Push notification system alerting registered students of available hot meals with reserved claim barcodes.',
    createdBy: 'Prof. Robert Vance',
    createdById: 'admin-robert',
    createdAt: '2026-02-05T09:30:00Z',
    status: 'Completed',
    featured: false,
  }
];

export const SEED_TEAMS = [
  {
    id: 'team-waste-warriors',
    name: 'EcoVisionaries',
    projectId: 'proj-waste-ai',
    projectTitle: 'AI-Based Campus Waste Classification & Analytics',
    leaderId: 'user-alex',
    leaderName: 'Alex Chen',
    leaderAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    memberIds: ['user-alex', 'user-sophia'],
    members: [
      { id: 'user-alex', name: 'Alex Chen', role: 'Team Lead & Cloud Backend', avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80', skills: ['Python', 'Firebase', 'FastAPI'] },
      { id: 'user-sophia', name: 'Sophia Patel', role: 'AI / CV Engineer', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&auto=format&fit=crop&q=80', skills: ['PyTorch', 'Computer Vision', 'Machine Learning'] }
    ],
    maxMembers: 4,
    requiredSkills: ['Python', 'Computer Vision', 'React', 'UI/UX Design'],
    description: 'Developing the edge camera classification pipeline and real-time dashboard. Currently looking for a Frontend & UI/UX specialist to finalize our student leaderboard.',
    status: 'In Progress',
    deadline: '2026-05-15',
    progress: 55,
    createdAt: '2026-01-20T14:00:00Z',
  },
  {
    id: 'team-transit-cloud',
    name: 'VelocityEdge',
    projectId: 'proj-micro-cloud',
    projectTitle: 'Serverless Edge Microservices for Campus Transit',
    leaderId: 'user-tariq',
    leaderName: 'Tariq Al-Mansoor',
    leaderAvatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=200&auto=format&fit=crop&q=80',
    memberIds: ['user-tariq', 'user-elena'],
    members: [
      { id: 'user-tariq', name: 'Tariq Al-Mansoor', role: 'Systems Architect', avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=200&auto=format&fit=crop&q=80', skills: ['Go (Golang)', 'Kubernetes', 'Docker'] },
      { id: 'user-elena', name: 'Elena Rostova', role: 'Security & Infrastructure', avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200&auto=format&fit=crop&q=80', skills: ['Cybersecurity & Pentesting', 'Docker', 'Python'] }
    ],
    maxMembers: 5,
    requiredSkills: ['Go (Golang)', 'Docker', 'Kubernetes', 'React', 'TypeScript'],
    description: 'High-speed distributed routing microservices. Looking for a React / mobile frontend developer to consume our WebSocket streams.',
    status: 'In Progress',
    deadline: '2026-06-01',
    progress: 40,
    createdAt: '2026-01-26T10:00:00Z',
  },
  {
    id: 'team-health-triage',
    name: 'MedPulse Devs',
    projectId: 'proj-tele-triage',
    projectTitle: 'AI Medical Tele-Triage & Symptom Visualizer',
    leaderId: 'user-aisha',
    leaderName: 'Aisha Bello',
    leaderAvatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=200&auto=format&fit=crop&q=80',
    memberIds: ['user-aisha', 'user-marcus'],
    members: [
      { id: 'user-aisha', name: 'Aisha Bello', role: 'Health Informatics & ML', avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=200&auto=format&fit=crop&q=80', skills: ['Python', 'Natural Language Processing', 'FastAPI'] },
      { id: 'user-marcus', name: 'Marcus Brody', role: 'UI/UX & Product Design', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80', skills: ['UI/UX Design', 'Figma', 'React', 'CSS3 / Tailwind'] }
    ],
    maxMembers: 4,
    requiredSkills: ['Python', 'React', 'Natural Language Processing', 'Docker'],
    description: 'Transforming clinical intake into an intuitive 3D symptom visualization interface. Seeking a backend/database specialist.',
    status: 'In Progress',
    deadline: '2026-05-30',
    progress: 60,
    createdAt: '2026-01-29T16:00:00Z',
  }
];

export const SEED_JOIN_REQUESTS = [
  {
    id: 'req-1',
    teamId: 'team-waste-warriors',
    teamName: 'EcoVisionaries',
    projectId: 'proj-waste-ai',
    projectTitle: 'AI-Based Campus Waste Classification & Analytics',
    studentId: 'user-marcus',
    studentName: 'Marcus Brody',
    studentAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    studentDepartment: 'Human-Computer Interaction',
    studentSkills: ['UI/UX Design', 'Figma', 'React', 'CSS3 / Tailwind'],
    message: 'Hey Alex! I saw your EcoVisionaries project. I can build the interactive 3D waste dashboard and gamified student leaderboard in React & Tailwind!',
    compatibilityScore: 94,
    status: 'pending',
    createdAt: '2026-02-08T09:20:00Z',
  },
  {
    id: 'req-2',
    teamId: 'team-transit-cloud',
    teamName: 'VelocityEdge',
    projectId: 'proj-micro-cloud',
    projectTitle: 'Serverless Edge Microservices for Campus Transit',
    studentId: 'user-lucas',
    studentName: 'Lucas Silva',
    studentAvatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200&auto=format&fit=crop&q=80',
    studentDepartment: 'Mobile & Cloud Applications',
    studentSkills: ['React', 'JavaScript', 'Firebase', 'UI/UX Design'],
    message: 'Hi Tariq, I would love to build the mobile-responsive passenger UI that connects with your Go WebSocket feed.',
    compatibilityScore: 88,
    status: 'pending',
    createdAt: '2026-02-07T14:15:00Z',
  }
];

export const SEED_NOTIFICATIONS = [
  {
    id: 'notif-1',
    userId: 'user-alex',
    type: 'join_request',
    title: 'New Team Join Request',
    message: 'Marcus Brody requested to join EcoVisionaries for "AI-Based Campus Waste Classification". Compatibility: 94%',
    read: false,
    createdAt: '2026-02-08T09:20:00Z',
  },
  {
    id: 'notif-2',
    userId: 'user-alex',
    type: 'project_recommendation',
    title: '96% Project Match Discovered!',
    message: '"Serverless Edge Microservices for Campus Transit" strongly matches your Python, Docker, and Cloud profile.',
    read: false,
    createdAt: '2026-02-07T11:00:00Z',
  },
  {
    id: 'notif-3',
    userId: 'user-alex',
    type: 'system',
    title: 'Welcome to SkillMatch Cloud',
    message: 'Your profile is set up! Explore project recommendations or discover complementary teammates.',
    read: true,
    createdAt: '2026-01-10T10:05:00Z',
  }
];
